@startuml

title Block-Badge.edu

skinparam monochrome true
skinparam dpi 300

autonumber

actor Student
actor Provider
database "Etherium"

== Provider ==

Provider -> Course: createCourse
note right: "Ethereum101", Provider, URL
activate Course
Course -> Course: Retrieve Course Image (unbaked)
Course -> Provider: getCourseValidityAndCriteria
Provider -> Course: Send CourseValidityAndCriteriaURL
Course -> Course: Set Course Tags
Course -> Provider: Course created
deactivate Course

== Student ==

Student -> Course: Take Course
note right: Student
Course -> Course: Test Passed
note left: Does course require test?
Course -> Provider: Course completed

== Badge Workflow ==

Provider -> Badge: Issue Badge
note left: Course, Student, Provider
activate Badge
Badge -> Badge: Assign Issue and Expiration date
Badge -> Badge: GetBakedImageURL
Badge -> Provider: Badge Ready
deactivate Badge
Provider -> Etherium: record
note right: Badge

  box "Blockchains"
    participant Etherium
  end box

actor Consumer

== Student ==

Student -> Etherium: authorizeViewing
note right: Consumer

==  ==

== Consumer ==

Consumer -> Etherium: getAllBadges
note right: Student

==  ==

@enduml
